// apps/functions/src/index.spec.ts
import { z } from 'zod';
const functionsTest = require('firebase-functions-test');

// Mock the custom initializeAdminApp function BEFORE it's called by importing index.ts.
// This prevents the real Admin SDK from initializing and conflicting with the test SDK.
jest.mock('@rac/data-access-firebase-admin', () => ({
  initializeAdminApp: jest.fn(),
}));

// Initialize the test SDK in offline mode. This will manage the mock app lifecycle.
const testEnv = functionsTest();

// Mock onCallGenkit to prevent it from running during test setup.
jest.mock('firebase-functions/v2/https', () => ({
  ...jest.requireActual('firebase-functions/v2/https'),
  onCallGenkit: jest.fn(),
}));

// Mock the Genkit AI object and its methods.
const mockEmbed = jest.fn();
const mockFlowRun = jest.fn();
jest.mock('genkit', () => ({
  genkit: () => ({
    defineFlow: (config: any, implementation: any) => {
      const mockFlow = (...args: any[]) => implementation(...args);
      (mockFlow as any).run = implementation;
      return mockFlow;
    },
    embed: mockEmbed,
  }),
  z,
}));

// Mock the entire 'firebase-admin/firestore' module.
// This is more stable than spying on an initialized service.
const mockUpdate = jest.fn().mockResolvedValue(true);
const mockFindNearest = jest.fn();
jest.mock('firebase-admin/firestore', () => ({
  getFirestore: jest.fn(() => ({
    collection: jest.fn(() => ({
      doc: jest.fn(() => ({
        update: mockUpdate,
      })),
      findNearest: mockFindNearest,
    })),
  })),
  FieldValue: {
    vector: (arr: number[]) => arr,
  },
}));

// Import the functions to test AFTER all mocks are in place.
import * as index from './index';
import { logger } from 'firebase-functions';

// Spy on and suppress logger output.
jest.spyOn(logger, 'info').mockImplementation();
jest.spyOn(logger, 'log').mockImplementation();
jest.spyOn(logger, 'warn').mockImplementation();

describe('Cloud Functions', () => {
  // Clear all mock histories after each test.
  afterEach(() => {
    jest.clearAllMocks();
  });

  // Clean up the test environment after all tests have run.
  afterAll(() => {
    testEnv.cleanup();
  });

  describe('onKnowledgeBaseCreate', () => {
    it('should call the knowledgeBaseEmbedder flow with document data', async () => {
      // Arrange
      const snap = testEnv.firestore.makeDocumentSnapshot(
        { content: 'This is the content to be embedded.' },
        'knowledge_bases/test-doc-123'
      );
      const embedderSpy = jest
        .spyOn(index.knowledgeBaseEmbedder, 'run')
        .mockImplementation(mockFlowRun);
      const wrapped = testEnv.wrap(index.onKnowledgeBaseCreate);

      // Act
      await wrapped(snap);

      // Assert
      expect(mockFlowRun).toHaveBeenCalledTimes(1);
      expect(mockFlowRun).toHaveBeenCalledWith({
        docId: 'test-doc-123',
        content: 'This is the content to be embedded.',
      });
      embedderSpy.mockRestore();
    });
  });

  describe('searchKnowledgeBaseFlow', () => {
    it('should embed a query and perform a vector search with a custom limit', async () => {
      // Arrange
      mockEmbed.mockResolvedValue([{ embedding: [0.1, 0.2, 0.3] }]);
      mockFindNearest.mockReturnValue({
        get: jest.fn().mockResolvedValue({
          docs: [
            { id: 'doc1', data: () => ({ content: 'result one' }) },
            { id: 'doc2', data: () => ({ content: 'result two' }) },
          ],
        }),
      });

      const query = 'find similar documents';
      const topN = 2;

      // Act
      const results = await index.searchKnowledgeBaseFlow({ query, topN });

      // Assert
      expect(mockEmbed).toHaveBeenCalledWith({
        embedder: expect.any(Object),
        content: query,
      });
      expect(mockFindNearest).toHaveBeenCalledWith(
        'embedding',
        [0.1, 0.2, 0.3],
        { limit: topN, distanceMeasure: 'COSINE' }
      );
      expect(results).toHaveLength(2);
    });
  });

  describe('helloWorld', () => {
    it('should send a hello message', () => {
      const mockReq = {} as any;
      const mockRes = { send: jest.fn() } as any;
      index.helloWorld(mockReq, mockRes);
      expect(mockRes.send).toHaveBeenCalledWith(
        'Hello from Firebase - Generated by @nx-toolkits/firebase!'
      );
    });
  });
});