name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout full history for Nx affected detection
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Node.js + npm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3) Install deps
      - run: npm ci --legacy-peer-deps

      # 4) Prettier formatting check
      - name: Check formatting
        run: npx nx format:check --all

      # 5) ESLint / module-boundary lint
      - name: Lint affected projects
        run: npx nx affected --target=lint --parallel

      # 6) Run unit tests (Jest) for affected projects
      - name: Test affected projects
        run: npx nx affected --target=test --parallel

      # 7) Build only what changed
      - name: Build affected projects
        run: npx nx affected --target=build --parallel

      # 8) End-to-end tests against local emulators
      - name: E2E tests with Playwright & Firebase Emulators
        run: |
          npm install -g firebase-tools
          firebase emulators:exec "npx nx e2e extension-e2e"

      # 9) Upload code coverage or artifacts here
      - name: Upload coverage
        uses: codecov/codecov-action@v3
