name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout full history for Nx affected detection
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Setup Node.js and cache npm modules
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4) Prettier formatting check
      - name: Check formatting
        run: npx nx format:check --all

      # 5) ESLint / module-boundary lint on affected projects
      - name: Lint affected projects
        run: npx nx affected --target=lint --parallel

      # 6) Run unit tests for affected projects
      - name: Test affected projects
        run: npx nx affected --target=test --parallel

      # 7) Build only the affected projects
      - name: Build affected projects
        run: npx nx affected --target=build --parallel

      # 8) Always build the Cloud Functions project
      - name: Build Cloud Functions
        run: npx nx build functions

      # 9) Install firebase-admin in functions workspace to satisfy emulator
      - name: Install firebase-admin for emulator
        run: npm install --save firebase-admin

      # 10) Cache Firestore emulator JAR to speed up CI
      - name: Cache Firestore Emulator JAR
        uses: actions/cache@v3
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulator-cache

      # 11) Install a pinned version of firebase-tools
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@14.9.0

      # 12) End-to-end tests with Playwright against the Firebase Emulator Suite
      - name: E2E tests with Playwright & Firebase Emulators
        run: |
          firebase emulators:exec "npx nx e2e extension-e2e"
